apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakao-deployment
  labels:
    app: kakao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakao
  template:
    metadata:
      labels:
        app: kakao
    spec:
      containers:
      - name: kakao
        image: sinjy1203/kakao:latest
        ports:
        - containerPort: 1204
        args: ["python", "main.py"]
        resources:
          requests:
            memory: 1Gi
            cpu: "0.5"
          limits:
            memory: 2Gi
            cpu: "1"
        env:
        - name: RAG_BASE_URL
          value: "http://rag-service.default:1200"
        volumeMounts:
        - mountPath: /kakao
          name: kakao-src
      volumes:
      - name: kakao-src
        hostPath:
          type: Directory
          path: {{ .Values.kakao_src_path }}

