kind: Deployment
apiVersion: apps/v1
metadata:
  name: llm-deployment
  labels:
    app: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        ports:
        - containerPort: 8000
        args: ["--model", "/model-awq", "--quantization", "awq", "--gpu-memory-utilization", "0.7"]
        resources:
          limits:
            nvidia.com/gpu: 2
            memory: 8Gi
            cpu: "4"
        volumeMounts:
        - mountPath: /model-awq
          name: vllm-model
      volumes:
      - name: vllm-model
        hostPath:
          type: Directory
          path: {{ .Values.LLM_path }}
